### ISSUE TITLE
Can I get the tracked libtorch model file?

### ISSUE THREAD

**Issue by Backlory** [mribrahim/PESMOD#1]
This is a very rare dataset! 
May I ask you a question - as indicated in 
 [https://github.com/mribrahim/PESMOD/blob/5972406505fd0dc42af1df8b68f9a5e9fdceaac6/src/main.cpp#L53](line 53) of src/main.cpp, where can I download the *.pt model file tracked by libtorch？ Could you have any plan of publishing the weights for the pre-trained model？

**Comment by mribrahim** [comment]
I have added the pre-trained model used in similarity.
