### ISSUE TITLE
What is the masks?

### ISSUE THREAD

**Issue by junmuzi** [mribrahim/PESMOD#3]
Hi,

Is the directory of "/home/ibrahim/SCBU-PESMOD-results/" empty? If not, what's the masks? Where can we get the masks for "Pexels-Marian"? Thank you very much.

The original issues is descripted as follows:
When I run 

./performance -d "/home/ibrahim/PESMOD/" -m "/home/ibrahim/SCBU-PESMOD-results/" -f "Pexels-Marian"

The output is 
...
filename: frame0622.jpg
 sequence: /home/sda/lijun/data/PESMOD/Pexels-Marian/
 totalGT: 0
 (totalTP + totalFN): 0
 totalFound: 0
 intersectRatio average: -nan
 precision: -nan  recall: -nan  f1: -nan  pwc: -nan

So I suspect the problem is that I don't have a masks file.

**Comment by mribrahim** [comment]
You can find the masks with any algorithm for motion/foreground detection. In src folder, there is a simple background subtraction code for motion detection, you can use it to find motion mask and add a few lines to save the mask outputs in png/jpg files.

In brief, the performance code aims to compare any mask (you have found with an algorithm) with the ground truth boxes of PESMOD dataset

**Comment by junmuzi** [comment]
Thank you for your kindly helps. Could you give the detailed command line that can run the codes in src folder? Because I do not know how to use these codes to achieve the motion detection. Thanks gain.

> You can find the masks with any algorithm for motion/foreground detection. In src folder, there is a simple background subtraction code for motion detection, you can use it to find motion mask and add a few lines to save the mask outputs in png/jpg files.
> 
> In brief, the performance code aims to compare any mask (you have found with an algorithm) with the ground truth boxes of PESMOD dataset

**Comment by mribrahim** [comment]
The motion detection code does not require a command line argument. You can download the PESMOD dataset and then modify the path in line 29 in main.cpp to set the exact path of the dataset in your machine.

**Comment by junmuzi** [comment]
> The motion detection code does not require a command line argument. You can download the PESMOD dataset and then modify the path in line 29 in main.cpp to set the exact path of the dataset in your machine.

Thank you very much. Could you help to tell me what the setting up environment to run these codes.

The following is that I used currently:
opencv-4.7.0
pytorch: 1.13.1
python:3.7.16
cuda:11.7
GPU: GTX 3090

Is above setting up ok? Could you share the setting up environments? Thanks a lot.

**Comment by mribrahim** [comment]
Mine is as follows, but I guess different version will not be a problem except libtorch (Pytorch C++ API):

OpenCV 4.4.0
CUDA 10.1
libtorch 1.11.0
